I_Value.WebApp/IValue/Controllers/ClientAndBranchMasterNewController.cs
using I_Value.WebApp.Models;
using IvalueDataAccess;
using IValuePublishProject.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IValuePublishProject.Controllers
{
    public class ClientAndBranchMasterNewController : Controller
    {
        // GET: ClientAndBranchMasterNew
        SQLDataAccess sqlDataAccess;
        Hashtable hInputPara;
        VMClientAndBranchMasterNew vMClientAndBranchMasterNew;
        ival_ClientAndBranchMasterNew objBranch = new ival_ClientAndBranchMasterNew();
        ival_DepartmentList ival_DepartmentList1 = new ival_DepartmentList();
      
        public ActionResult Index()
        {
            try
            {
                hInputPara = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                DataTable dtClient = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetClientAndBranch");

                List<ival_ClientAndBranchMasterNew> listClient = new List<ival_ClientAndBranchMasterNew>();

                if (dtClient.Rows.Count > 0)

                {
                    for (int i = 0; i < dtClient.Rows.Count; i++)
                    {

                        listClient.Add(new ival_ClientAndBranchMasterNew
                        {
                            Branch_ID = Convert.ToInt32(dtClient.Rows[i]["branch_id"]),
                            Client_ID = Convert.ToInt32(dtClient.Rows[i]["client_id"]),
                            Client_Name = Convert.ToString(dtClient.Rows[i]["client_name"]),
                            Branch_Name = Convert.ToString(dtClient.Rows[i]["branch_name"]),
                            Branch_State = Convert.ToString(dtClient.Rows[i]["state"]),
                            
                        });
                    }
                }
                return View(listClient);

            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
            //return View();
        }

        public ActionResult AddBranchNew()
        {
            vMClientAndBranchMasterNew = new VMClientAndBranchMasterNew();
            vMClientAndBranchMasterNew.ival_StatesList = GetState();
            vMClientAndBranchMasterNew.ival_DistrictsList = GetDistricts();
            vMClientAndBranchMasterNew.ival_CitiesList = GetCity();
            vMClientAndBranchMasterNew.ival_LocalityList = GetLocality();
            vMClientAndBranchMasterNew.ival_ClientList = GetClient();
            vMClientAndBranchMasterNew.ival_DepartmentList = GetDepartment();
            vMClientAndBranchMasterNew.ival_Des =GetDes();
            return View(vMClientAndBranchMasterNew);
        }

        [HttpPost]
        public ActionResult AddBranchNew(String str, String DeptList)
        {
            string resultStr = string.Empty;
            DataTable list1 = (DataTable)JsonConvert.DeserializeObject(str, (typeof(DataTable)));
            DataTable DeptList1 = (DataTable)JsonConvert.DeserializeObject(DeptList, (typeof(DataTable)));
            try
            {
                for (int i = 0; i < list1.Rows.Count; i++)
                {

                    
                    hInputPara = new Hashtable();
                    sqlDataAccess = new SQLDataAccess();
                   

                    IEnumerable<ival_States> ival_StatesList = GetState();
                    var state = ival_StatesList.AsEnumerable().Where(row => row.State_ID == vMClientAndBranchMasterNew.SelectedStateID).Select(row => row.State_Name.ToString());

                    IEnumerable<ival_Districts> ival_DistrictsList = GetDistricts();
                    var Dist = ival_DistrictsList.AsEnumerable().Where(row => row.District_ID == vMClientAndBranchMasterNew.SelectedDistID).Select(row => row.District_Name.ToString());

                    IEnumerable<ival_Cities> ival_CitiesList = GetCity();
                    var City = ival_CitiesList.AsEnumerable().Where(row => row.Loc_Id == vMClientAndBranchMasterNew.SelectedCityID).Select(row => row.City_Name.ToString());

                    IEnumerable<ival_Locality> ival_LocalityList = GetLocality();
                    var Loc = ival_LocalityList.AsEnumerable().Where(row => row.Loc_Id == vMClientAndBranchMasterNew.SelectedLocID).Select(row => row.Loc_Name.ToString());

                    var pincode = ival_LocalityList.AsEnumerable().Where(row => row.Loc_Id == vMClientAndBranchMasterNew.SelectedBranchPincode).Select(row => row.Pin_Code.ToString());

                    IEnumerable<ival_ClientMaster> ival_ClientList = GetClient();
                    var Client = ival_ClientList.AsEnumerable().Where(row => row.Client_ID == vMClientAndBranchMasterNew.SelectedClientID).Select(row => row.Client_Name.ToString());

                    /*IEnumerable<ival_LookupCategoryValues> ival_DepartmentList = GetDepartment();
                    var Dept = ival_DepartmentList.AsEnumerable().Where(row => row.Lookup_ID == vMClientAndBranchMasterNew.SelectedDeptID).Select(row => row.Lookup_Value.ToString());*/

                    hInputPara.Add("@Client_Id", Convert.ToInt32(list1.Rows[i]["Client_ID"]));
                    hInputPara.Add("@Branch_Name", Convert.ToString(list1.Rows[i]["Branch_Name"]));
                    hInputPara.Add("@Br_Address1", Convert.ToString(list1.Rows[i]["Br_Addr1"]));
                    hInputPara.Add("@Br_Address2", Convert.ToString(list1.Rows[i]["Br_Addr2"]));
                    hInputPara.Add("@Br_State", Convert.ToString(list1.Rows[i]["Br_State"]));
                    hInputPara.Add("@Br_District", Convert.ToString(list1.Rows[i]["Br_Dist"]));
                    hInputPara.Add("@Br_City", Convert.ToString(list1.Rows[i]["Br_City"]));
                    hInputPara.Add("@Br_Locality", Convert.ToString(list1.Rows[i]["Br_Loc"]));
                    hInputPara.Add("@Br_Pincode", Convert.ToString(list1.Rows[i]["Br_Pin"]));
                    hInputPara.Add("@Basic_Fees", Convert.ToString(list1.Rows[i]["Basic_Fees"]));
                    hInputPara.Add("@Additional_Fees", Convert.ToString(list1.Rows[i]["Add_Fees"]));
                    hInputPara.Add("@OutofGeo_Fees", Convert.ToString(list1.Rows[i]["Outof_Fees"]));
                    hInputPara.Add("@Total_Fees", Convert.ToString(list1.Rows[i]["Total_Fees"]));
                    hInputPara.Add("@Created_By", string.Empty);

                    var result = sqlDataAccess.ExecuteStoreProcedure("usp_InsertClientAndBranch", hInputPara);

                  
                    Hashtable hInputPara1 = new Hashtable();
                    for (int j = 0; j < DeptList1.Rows.Count; j++)
                        {

                        hInputPara1.Add("@Client_Id", result);
                       // hInputPara1.Add("@Client_Id", Convert.ToInt32(DeptList1.Rows[j]["Client_ID"]));
                        hInputPara1.Add("@Client_Dept", Convert.ToString(DeptList1.Rows[j]["Client_Dept"]));
                        hInputPara1.Add("@Client_Name", Convert.ToString(DeptList1.Rows[j]["Client_Name"]));
                        hInputPara1.Add("@Client_No", Convert.ToString(DeptList1.Rows[j]["Client_No"]));
                        hInputPara1.Add("@Client_Desgn", Convert.ToString(DeptList1.Rows[j]["Client_Desgn"]));
                        hInputPara1.Add("@Client_Email", Convert.ToString(DeptList1.Rows[j]["Client_Email"]));
                        hInputPara1.Add("@Dept_Id", Convert.ToString(DeptList1.Rows[j]["Dept_Id"]));
                        hInputPara1.Add("@Created_By", string.Empty);
                        //insert clientDept parameter
                        var result1 = sqlDataAccess.ExecuteStoreProcedure("usp_InsertDepartmentNew", hInputPara1);
                        if(Convert.ToInt32(result1) == 1)
                        {
                            hInputPara1.Clear();
                        }
                    }
                       
                }
            }
            catch (Exception e)
            {
                //e.InnerException.ToString();
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = true, Message = "SuccessFull" }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult EditBranchNew(int? ID)
       
        {
            if (string.IsNullOrEmpty(ID.ToString()))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                //return View();
            }
            vMClientAndBranchMasterNew = new VMClientAndBranchMasterNew();
            objBranch = new ival_ClientAndBranchMasterNew();
            var items = new List<SelectListItem>();
            sqlDataAccess = new SQLDataAccess();
            hInputPara = new Hashtable();
            try
            {
                hInputPara.Add("@Client_ID", ID);
                DataTable dtBranch = sqlDataAccess.GetDatatableExecuteStoreProcedure("[usp_GetClientAndBranchMasterByID]", hInputPara);

                if (dtBranch.Rows.Count > 0 && dtBranch != null)
                {
                    /*object valuedtbranchid = Convert.ToInt32(dtBranch.Rows[0]["branch_id"]);
                    if (dtBranch.Columns.Contains("branch_id") && valuedtbranchid != null && valuedtbranchid.ToString() != "")
                        objBranch.Branch_Id = Convert.ToInt32(valuedtbranchid);
                    else
                        objBranch.Branch_Id = 0;*/

                    object valuedtClient = Convert.ToInt32(dtBranch.Rows[0]["client_id"]);
                    if (dtBranch.Columns.Contains("client_id") && valuedtClient != null && valuedtClient.ToString() != "")
                        objBranch.Client_ID = Convert.ToInt32(valuedtClient);
                    else
                        objBranch.Client_ID = 0;

I_Value.WebApp/IValue/Views/ClientAndBranchMasterNew/Index.cshtml
@model IEnumerable<IValuePublishProject.Models.ival_ClientAndBranchMasterNew>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IvalueMasterPage.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="padding-left:10px;"> Client & branch List  </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="content bg">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="search-container">
                                    <form>
                                        @*<input type="text" placeholder="Search.." name="search">
                                        <button type="submit"><i class="fa fa-search"></i></button>*@
                                        @using (Html.BeginForm("Index", "ClientAndBranchMasterNew", FormMethod.Post))
                                        {
                                            <a class="btn btn-success btn-sm pull-right" href="@Url.Action("AddBranchNew","ClientAndBranchMasterNew")">Add New Branch</a>
                                        }
                                        @*<a class="btn btn-success btn-sm pull-right" href="client & branch-master.html">Add New Branch</a>*@
                                    </form>
                                    
                                </div>
                                <br>
                                <br />
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered tblss">
                                        <thead>
                                            <tr>
                                                <th width="210">Client</th>
                                                <th width="172">State</th>
                                                <th width="202">Branch</th>
                                                <th width="129">View </th>
                                                <th width="87">Edit</th>

                                                <th width="56">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                            <tr>
                                                <td width="210">
                                                    @Html.DisplayFor(modelItem => item.Client_Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Branch_State)
                                                </td>
                                                <td width="210">
                                                    @Html.DisplayFor(modelItem => item.Branch_Name)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("ViewBranchNew", "ClientAndBranchMasterNew", new { id = item.Client_ID })">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("EditBranchNew", "ClientAndBranchMasterNew", new { id = item.Client_ID })">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                </td>

                                                <td>
                                                    <a>
                                                        <i class="fa fa-trash" aria-hidden="true" onclick="ConfirmDelete(@item.Branch_ID);"></i>
                                                    </a>

                                                </td>
                                            </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .animated -->
        </div>
        <!-- Default box -->
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script>
     function ConfirmDelete(Id) {
            var str = Id;
            var x = confirm("Are you sure you want to delete?");
            if (x) {
               $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "ClientAndBranchMasterNew")',
            data: { ID: str },
            success: function (data) {
                //$("#divLoader").hide();
                   alert('Branch Deleted successfully')
                window.location.reload();
            },
        });
            }
            else
                return
        }
</script>