I_Value.WebApp/IValue/Controllers/Ival_EmployeeController.cs
using I_Value.WebApp.Models;
using IvalueDataAccess;
using IValuePublishProject.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace I_Value.WebApp.Controllers
{

    public class Ival_EmployeeController : Controller
    {

        SQLDataAccess sqlDataAccess;
        Hashtable hInputPara;
        IvalueDataModel Datamodel = new IvalueDataModel();
        VMEmployeeMaster vMEmployeeMaster;
        ival_EmployeeMaster objEmp;

        // GET: Ival_Employee
        public ActionResult Index()
        {
            try
            {
                hInputPara = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                IEnumerable<ival_BranchMaster> ival_BranchMastersList = GetBranch();
                IEnumerable<ival_RoleMaster> ival_RoleMasters = GetRoles();
                DataTable dtEmployee = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetEmployees");

                List<VMEmployeeMaster> listEmp = new List<VMEmployeeMaster>();

                if (dtEmployee.Rows.Count > 0 && dtEmployee != null)

                {
                    for (int i = 0; i < dtEmployee.Rows.Count; i++)
                    {
                        var branchName = ival_BranchMastersList.Where(row => row.Branch_ID == Convert.ToInt32(dtEmployee.Rows[i]["Branch_ID"])).Select(p => p.Branch_Name.ToString());
                        var roleName = ival_RoleMasters.Where(row => row.Role_ID == Convert.ToInt32(dtEmployee.Rows[i]["Role_ID"])).Select(p => p.Role_Name.ToString());
                        listEmp.Add(new VMEmployeeMaster
                        {
                            current_status = Convert.ToString(dtEmployee.Rows[i]["current_status"]),
                            Employee_ID = Convert.ToInt16(dtEmployee.Rows[i]["Employee_ID"]),
                            Company_Email_ID = Convert.ToString(dtEmployee.Rows[i]["Company_Email_ID"]),
                            First_Name = Convert.ToString(dtEmployee.Rows[i]["First_Name"]),

                            Branch_Name = branchName.FirstOrDefault(),
                            Role_Name = Convert.ToString(dtEmployee.Rows[i]["Role_Name"])

                        }); ;

                    }
                }
                return View(listEmp);
            }

            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult AddEmployee()
        {
            vMEmployeeMaster = new VMEmployeeMaster();
            vMEmployeeMaster.ival_BranchMastersList = GetBranch();
            vMEmployeeMaster.ival_RoleMastersList = GetRoles();
            vMEmployeeMaster.ival_LocalityList = GetLocality();
            vMEmployeeMaster.ival_StatesList = GetState();
            vMEmployeeMaster.ival_CitiesList = GetCity();
            vMEmployeeMaster.ival_DistrictsList = GetDistricts();
            //vMEmployeeMaster.pincodeList = GetPincode();
            vMEmployeeMaster.relationWithEmpList = GetRelationsWithEmp();
            vMEmployeeMaster.banklist = Getbank();
            vMEmployeeMaster.bloodGrpList = GetBloodGrp();
            vMEmployeeMaster.currentstatus = GetCurrent();
            return View(vMEmployeeMaster);
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            if (string.IsNullOrEmpty(ID.ToString()))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                //return View();
            }
            vMEmployeeMaster = new VMEmployeeMaster();
            objEmp = new ival_EmployeeMaster();
            var items = new List<SelectListItem>();
            sqlDataAccess = new SQLDataAccess();
            hInputPara = new Hashtable();
            try
            {
                hInputPara.Add("@Employee_ID", ID);
                DataTable dtEmp = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetEmployeesByEmpId", hInputPara);

                if (dtEmp.Rows.Count > 0 && dtEmp != null)

                {
                    vMEmployeeMaster.relationWithEmpList = GetRelationsWithEmp();
                    vMEmployeeMaster.banklist = Getbank();
                    object valueEmployee_ID = Convert.ToInt32(dtEmp.Rows[0]["Employee_ID"]);
                    if (dtEmp.Columns.Contains("Employee_ID") && valueEmployee_ID != null)
                        objEmp.Employee_ID = Convert.ToInt32(valueEmployee_ID);
                    else
                        objEmp.Employee_ID = 0;

                    object valueFirst_Name = dtEmp.Rows[0]["First_Name"];
                    if (dtEmp.Columns.Contains("First_Name") && valueFirst_Name != null && valueFirst_Name.ToString() != "")
                        objEmp.First_Name = dtEmp.Rows[0]["First_Name"].ToString();
                    else
                        objEmp.First_Name = string.Empty;


                    object valueMiddle_Name = dtEmp.Rows[0]["Middle_Name"];
                    if (dtEmp.Columns.Contains("Middle_Name") && valueMiddle_Name != null && valueMiddle_Name.ToString() != "")
                        objEmp.Middle_Name = dtEmp.Rows[0]["Middle_Name"].ToString();
                    else
                        objEmp.Middle_Name = string.Empty;

                    object valueLast_Name = dtEmp.Rows[0]["Last_Name"];
                    if (dtEmp.Columns.Contains("Last_Name") && valueLast_Name != null && valueLast_Name.ToString() != "")
                        objEmp.Last_Name = dtEmp.Rows[0]["Last_Name"].ToString();
                    else
                        objEmp.Last_Name = string.Empty;

                    object valueCompany_Email_ID = dtEmp.Rows[0]["Company_Email_ID"];
                    if (dtEmp.Columns.Contains("Company_Email_ID") && valueCompany_Email_ID != null && valueCompany_Email_ID.ToString() != "")
                        objEmp.Company_Email_ID = dtEmp.Rows[0]["Company_Email_ID"].ToString();
                    else
                        objEmp.Company_Email_ID = string.Empty;

                    object valueBranch_ID = dtEmp.Rows[0]["Branch_ID"];
                    if (dtEmp.Columns.Contains("Branch_ID") && valueBranch_ID != null)
                        objEmp.Branch_ID = Convert.ToInt32(dtEmp.Rows[0]["Branch_ID"].ToString());
                    else
                        objEmp.Branch_ID = 0;

                    object valueRole_ID = dtEmp.Rows[0]["Role_ID"];
                    if (dtEmp.Columns.Contains("Role_ID") && valueRole_ID != null)
                        objEmp.Role_ID = Convert.ToInt32(dtEmp.Rows[0]["Role_ID"].ToString());
                    else
                        objEmp.Role_ID = 0;


                    object valueContact_Number = dtEmp.Rows[0]["Contact_Number"];
                    if (dtEmp.Columns.Contains("Contact_Number") && valueContact_Number != null && valueContact_Number.ToString() != "")
                        vMEmployeeMaster.Contact_Number = Convert.ToString(dtEmp.Rows[0]["Contact_Number"].ToString());
                    else
                        vMEmployeeMaster.Contact_Number = string.Empty;

                    object valuePersonal_Email_ID = dtEmp.Rows[0]["Personal_Email_ID"];
                    if (dtEmp.Columns.Contains("Personal_Email_ID") && valuePersonal_Email_ID != null && valuePersonal_Email_ID.ToString() != "")
                        objEmp.Personal_Email_ID = dtEmp.Rows[0]["Personal_Email_ID"].ToString();
                    else
                        objEmp.Personal_Email_ID = string.Empty;

                    object valueCurrent_Address_1 = dtEmp.Rows[0]["Current_Address_1"];
                    if (dtEmp.Columns.Contains("Current_Address_1") && valueCurrent_Address_1 != null && valueCurrent_Address_1.ToString() != "")
                        objEmp.Current_Address_1 = dtEmp.Rows[0]["Current_Address_1"].ToString();
                    else
                        objEmp.Current_Address_1 = string.Empty;

                    object valueCurrent_Address_2 = dtEmp.Rows[0]["Current_Address_2"];
                    if (dtEmp.Columns.Contains("Current_Address_2") && valueCurrent_Address_2 != null && valueCurrent_Address_2.ToString() != "")
                        objEmp.Current_Address_2 = dtEmp.Rows[0]["Current_Address_2"].ToString();
                    else
                        objEmp.Current_Address_2 = string.Empty;

                    object valueCurrent_City1 = dtEmp.Rows[0]["Current_City1"];
                    if (dtEmp.Columns.Contains("Current_City1") && valueCurrent_City1 != null && valueCurrent_City1.ToString() != "")
                        objEmp.Current_City1 = dtEmp.Rows[0]["Current_City1"].ToString();
                    else
                        objEmp.Current_City1 = string.Empty;

                    object valueCurrent_State = dtEmp.Rows[0]["Current_State"];
                    if (dtEmp.Columns.Contains("Current_State") && valueCurrent_State != null && valueCurrent_State.ToString() != "")
                        objEmp.Current_State = dtEmp.Rows[0]["Current_State"].ToString();
                    else
                        objEmp.Current_State = string.Empty;

                    object valueCurrent_District = dtEmp.Rows[0]["Current_District"];
                    if (dtEmp.Columns.Contains("Current_District") && valueCurrent_District != null && valueCurrent_District.ToString() != "")
                        objEmp.Current_District = dtEmp.Rows[0]["Current_District"].ToString();
                    else
                        objEmp.Current_District = string.Empty;


                    object valueCurrent_City = dtEmp.Rows[0]["Current_City"];

I_Value.WebApp/IValue/Views/Ival_Employee/Index.cshtml
@model IEnumerable<I_Value.WebApp.Models.VMEmployeeMaster>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IvalueMasterPage.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="padding-left:10px;"> List Of Employees </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="content bg">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="search-container">
                                    @using (Html.BeginForm("Index", "Employee", FormMethod.Post))
                                    {
                                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("AddEmployee","Ival_Employee")">Add New Employee</a>

                                    }

                                </div><br>
                                <br />

                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered tblss">
                                        <thead>
                                            <tr>
                                               
                                                <th width="90">Emplyoee Id</th>
                                                <th width="120">Name</th>
												 <th width="110">Current Status</th>
                                                <th width="85">Role</th>
                                                <th width="120">Branch</th>
                                                <th width="164">Email Id.</th>
                                                <th width="26">View</th>
                                                <th width="26">Edit</th>
                                                <th width="26">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                            <tr>
                                               
                                               
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Employee_ID)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.First_Name)
                                                </td>
												 <td>
                                                    @Html.DisplayFor(modelItem => item.current_status)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Role_Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Branch_Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Company_Email_ID)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("ViewEmployeeDetails", "Ival_Employee", new { id = item.Employee_ID })">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                </td>

                                                <td>
                                                    <a href="@Url.Action("Edit", "Ival_Employee", new { id = item.Employee_ID })">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                </td>
                                                @*<td><a href="@Url.Action("Edit","Employee_ID" ,"Ival_Employee" ,new { id = item.Employee_ID },null)"><i class="fa fa-edit"></i></a></td>*@
                                                <td>
                                                    @*<i class="fa fa-trash" aria-hidden="true">@Html.ActionLink("Delete", "Delete", "Ival_Employee", new { id = item.Employee_ID }) </i>*@
                                                    @*<a href="@Url.Action("Delete", "Ival_Employee", new { id = item.Employee_ID })">*@
                                                    <a>
                                                        <i class="fa fa-trash" aria-hidden="true" onclick="ConfirmDelete(@item.Employee_ID);"></i>
                                                    </a>

                                                </td>

                                            </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .animated -->
        </div>
        <!-- Default box -->
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script>
             function ConfirmDelete(Id) {
            var str = Id;
            var x = confirm("Are you sure you want to delete?");
            if (x) {
               $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "Ival_Employee")',
            data: { ID: str },
            success: function (data) {
                //$("#divLoader").hide();
                   alert('Employee Deleted successfully')
                window.location.reload();
            },
        });
            }
            else
                return
        }
</script>