I_Value.WebApp/IValue/Controllers/BuilderAndCompanyController.cs
using I_Value.WebApp.Models;
using IvalueDataAccess;
using IValuePublishProject.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;

namespace I_Value.WebApp.Controllers
{
    public class BuilderAndCompanyController : Controller
    {
        VMBuilderGroupMaster vMBuilderGroupMaster;
        ival_BuilderGroupMaster ival_BuilderGroupMaster;
        ival_BuilderCompanyMaster ival_BuilderCompanyMaster;
        ival_BuilderCompanyMasterNew ival_BuilderCompanyMasterNew;
        SQLDataAccess sqlDataAccess;
        Hashtable hInputPara;
        // GET: BuilderAndCompany
        public ActionResult Index()
        {
           
            try
            {
                hInputPara = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                DataTable dtBuilderGroup = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetBuilderList");

                List<VMBuilderGroupMaster> vMBuilderGroupMasterList = new List<VMBuilderGroupMaster>();

                if (dtBuilderGroup.Rows.Count > 0 && dtBuilderGroup!=null)

                {
                    for (int i = 0; i < dtBuilderGroup.Rows.Count; i++)
                    {

                        vMBuilderGroupMasterList.Add(new VMBuilderGroupMaster
                        {
                            Builder_Group_Master_IDl = Convert.ToInt32(dtBuilderGroup.Rows[i]["Builder_Group_Master_ID"]),
                           // Builder_Company_Master_IDl = Convert.ToInt32(dtBuilderGroup.Rows[i]["Builder_Company_Master_ID"]),
                            BuilderGroupNamel = Convert.ToString(dtBuilderGroup.Rows[i]["BuilderGroupName"]),
                            Builder_Cityl = Convert.ToString(dtBuilderGroup.Rows[i]["Builder_City"]),
                            Builder_Statel = Convert.ToString(dtBuilderGroup.Rows[i]["Builder_State"])
                        });


                    }
                }
                return View(vMBuilderGroupMasterList);

            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Login", "Account");
            }
            
        }
        public ActionResult CompanyIndex()
        {

            try
            {
                hInputPara = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                DataTable dtBuilderGroup = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetCompanyBuilderListDetails");

                List<VMBuilderGroupMaster> vMBuilderGroupMasterList = new List<VMBuilderGroupMaster>();

                if (dtBuilderGroup.Rows.Count > 0 && dtBuilderGroup != null)

                {
                    for (int i = 0; i < dtBuilderGroup.Rows.Count; i++)
                    {

                        vMBuilderGroupMasterList.Add(new VMBuilderGroupMaster
                        {
                            Builder_Company_Master_IDl = Convert.ToInt32(dtBuilderGroup.Rows[i]["Builder_Company_Master_ID"]),
                             Builder_Company_Name = Convert.ToString(dtBuilderGroup.Rows[i]["Builder_Company_Name"]),
                            BuilderGroupNamel = Convert.ToString(dtBuilderGroup.Rows[i]["BuilderGroupName"]),
                            Builder_Cityl = Convert.ToString(dtBuilderGroup.Rows[i]["Builder_C_City"]),
                            Builder_Statel = Convert.ToString(dtBuilderGroup.Rows[i]["Builder_C_State"])
                        });


                    }
                }
                return View(vMBuilderGroupMasterList);

            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Login", "Account");
            }
            return View();
        }
        public ActionResult AddBuilder()
        {
            vMBuilderGroupMaster = new VMBuilderGroupMaster();
            vMBuilderGroupMaster.ival_StatesList = GetState();
            vMBuilderGroupMaster.ival_LocalityList = GetLocality();
            vMBuilderGroupMaster.ival_CitiesList = GetCity();
            vMBuilderGroupMaster.ival_DistrictsList = GetDistrict();
            vMBuilderGroupMaster.BuilderGroupList = GetBuilderList();
            return View(vMBuilderGroupMaster);
        }
        [HttpPost]
        public ActionResult AddBuilder(string str)
        {

            try
            {

                DataTable list1 = (DataTable)JsonConvert.DeserializeObject(str, (typeof(DataTable)));

                for (int i=0;i<list1.Rows.Count;i++)
                {
                    hInputPara = new Hashtable();
                    sqlDataAccess = new SQLDataAccess();


                    hInputPara.Add("@BuilderGroupName", Convert.ToString(list1.Rows[i]["BuilderGroupName"]));
                    hInputPara.Add("@Builder_Address1", Convert.ToString(list1.Rows[i]["officeAdd1"]));
                    hInputPara.Add("@Builder_Address2", Convert.ToString(list1.Rows[i]["officeAdd2"]));
                    hInputPara.Add("@Builder_Locality", Convert.ToString(list1.Rows[i]["ddlLocality"]));
                    hInputPara.Add("@Nearby_Landmark", Convert.ToString(list1.Rows[i]["nearByLandmark"]));
                    hInputPara.Add("@Builder_District", Convert.ToString(list1.Rows[i]["ddlDistrict"]));
                    hInputPara.Add("@Builder_City", Convert.ToString(list1.Rows[i]["ddlCity"]));
                    hInputPara.Add("@Builder_State", Convert.ToString(list1.Rows[i]["ddlstate"]));
                    hInputPara.Add("@Builder_Pincode", Convert.ToString(list1.Rows[i]["ddlPincode"]));
                    
                    hInputPara.Add("@Director_Name1", Convert.ToString(list1.Rows[i]["DirectorName1"]));
                    hInputPara.Add("@Director_Phone1", Convert.ToString(list1.Rows[i]["DirectorPhone1"]));
                    hInputPara.Add("@Director_Mobile1", Convert.ToString(list1.Rows[i]["DirectorMobile1"]));
                    hInputPara.Add("@Director_Email1", Convert.ToString(list1.Rows[i]["DirectorEmail1"]));
                    hInputPara.Add("@Director_Name2", Convert.ToString(list1.Rows[i]["DirectorName2"]));
                    hInputPara.Add("@Director_Phone2", Convert.ToString(list1.Rows[i]["DirectorPhone2"]));
                    hInputPara.Add("@Director_Mobile2", Convert.ToString(list1.Rows[i]["DirectorMobile2"]));
                    hInputPara.Add("@Director_Email2", Convert.ToString(list1.Rows[i]["DirectorEmail2"]));
                    hInputPara.Add("@Director_Name3", Convert.ToString(list1.Rows[i]["DirectorName3"]));
                   
                    hInputPara.Add("@Director_Phone3", Convert.ToString(list1.Rows[i]["DirectorPhone3"]));
                    hInputPara.Add("@Director_Mobile3", Convert.ToString(list1.Rows[i]["DirectorMobile3"]));
                   
                   
                    hInputPara.Add("@Director_Email3", Convert.ToString(list1.Rows[i]["DirectorEmail3"]));
                    hInputPara.Add("@Builder_Street", Convert.ToString(list1.Rows[i]["street"]));
                    hInputPara.Add("@Builder_Grade", Convert.ToString(list1.Rows[i]["BuilderGrade"]));

                    string result=sqlDataAccess.ExecuteStoreProcedure("usp_InsertBuilderGroup", hInputPara);
                    return Json(new { success = true, Message = "Insert Successfully" }, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception e)
            {
                e.InnerException.ToString();
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
            return Json("");
        }
        //[HttpPost]
        //public ActionResult AddBuilder(VMBuilderGroupMaster vMBuilderGroupMaster)
        //{

        //    try
        //    {

        //        //IEnumerable<ival_States> ival_StatesList = GetState();
        //        //var builderState = ival_StatesList.AsEnumerable().Where(row => row.State_ID == vMBuilderGroupMaster.SelectedBuilderStateId).Select(row => row.State_Name.ToString());

        //        //IEnumerable<ival_LookupCategoryValues> pincodeList = GetPincode();
        //        //var builderPincode = pincodeList.AsEnumerable().Where(row => row.Lookup_ID == vMBuilderGroupMaster.SelectedBuilderPincodeID).Select(row => row.Lookup_Value.ToString());


        //        //hInputPara = new Hashtable();
        //        //sqlDataAccess = new SQLDataAccess();

        //        //hInputPara = new Hashtable();

        //        //hInputPara.Add("@BuilderGroupName", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.BuilderGroupName));
        //        //hInputPara.Add("@Builder_Address1", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Builder_Address1));
        //        //hInputPara.Add("@Builder_Address2", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Builder_Address2));
        //        //hInputPara.Add("@Builder_Locality", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Builder_Locality));
        //        //hInputPara.Add("@Nearby_Landmark", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Nearby_Landmark));
        //        //hInputPara.Add("@Builder_District", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Builder_District));
        //        //hInputPara.Add("@Builder_City", Convert.ToString(vMBuilderGroupMaster.ival_BuilderGroupMaster.Builder_City));
        //        //hInputPara.Add("@Builder_State", builderState.FirstOrDefault());
        //        //hInputPara.Add("@Builder_Pincode ", builderPincode.FirstOrDefault());

I_Value.WebApp/IValue/Views/BuilderAndCompany/CompanyIndex.cshtml
@model IEnumerable<I_Value.WebApp.Models.VMBuilderGroupMaster>

@{
    ViewBag.Title = "CompanyIndex";
    Layout = "~/Views/Shared/_IvalueMasterPage.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="padding-left:10px;">Builder & Company </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="content bg">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="search-container">

                                    @using (Html.BeginForm("CompanyIndex", "BuilderAndCompany", FormMethod.Post))
                                    {
                                        @*<input type="text" id="search" placeholder="Search.." name="search">
                                        <button type="button"><i class="fa fa-search"></i></button>*@

                                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("CompanyMasterNew","BuilderAndCompany")">Add Company</a>

                                    }
                                </div>
                                <br>
                                <br />
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered tblss">
                                        <thead>
                                            <tr>
                                                <th width="187"> Builder Group Name</th>
                                                <th width="187">Company Name</th>
                                                <th width="132">City</th>
                                                <th width="210">State</th>
                                                <th width="106">View</th>                                              
                                                <th width="62">Edit</th>
                                                <th width="69">Approval</th>
                                                <th width="61">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                            <tr>
                                                <td width="192">
                                                    @Html.DisplayFor(modelItem => item.BuilderGroupNamel)
                                                </td>
                                                <td width="187">
                                                    @*<a href="@Url.Action("ViewCompanyDetailsByGroup", "BuilderAndCompany", new { id = item.Builder_Group_Master_IDl })"> @Html.DisplayFor(modelItem => item.BuilderGroupNamel)</a>*@
                                                    @Html.DisplayFor(modelItem => item.Builder_Company_Name)

                                                </td>
                                                <td width="192">
                                                    @Html.DisplayFor(modelItem => item.Builder_Cityl)
                                                </td>
                                                <td width="201">
                                                    @Html.DisplayFor(modelItem => item.Builder_Statel)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("ViewBuilderCompany", "BuilderAndCompany", new { ID = item.Builder_Company_Master_IDl })">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("EditCompanyMasterNew", "BuilderAndCompany", new { ID = item.Builder_Company_Master_IDl })">
                                                        <i class="fa fa-edit"></i>
                                                    </a>

                                                </td>

                                                @*<td>Approved</td>*@

                                                <td><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></td>
                                                <td>
                                                    @*<a href="@Url.Action("DeleteBuilderCompany", "BuilderAndCompany", new { ID = item.Builder_Company_Master_IDl })">
            <i class="fa fa-trash" aria-hidden="true"></i>
        </a>*@
                                                    <a>
                                                        <i class="fa fa-trash" aria-hidden="true" onclick="ConfirmDelete(@item.Builder_Company_Master_IDl);"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                        
                    </div>
                </div>
                <!-- .animated -->

            </div>

        </div>
        <!-- Default box -->
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script src="~/Scripts/jquery.min.js"></script>
<script type="text/javascript">
    function search() {
        var searchName= $("#search").val();
        console.log(searchName);
        @*var str = JSON.stringify(searchName);
            $.ajax({
            type: "POST",
            url: '@Url.Action("EditCompanyMasterNew", "BuilderAndCompany")',
            data: { str: str },
            Response: ContentType = 'application/json;charset=utf-8',
                success: function(data) {
                    console.log(data);
                //$("#divLoader").hide();
                    alert('Builder Company details submitted successfully');
                     var url = '@Url.Action("CompanyIndex", "BuilderAndCompany")';
                window.location.href = url;

            },
        });*@

    }

    function ConfirmDelete(Id) {
            var str = Id;
            var x = confirm("Are you sure you want to delete?");
            if (x) {
               $.ajax({
            type: "GET",
            url: '@Url.Action("DeleteBuilderCompany", "BuilderAndCompany")',
            data: { ID: str },
            success: function (data) {
                //$("#divLoader").hide();
                   alert('Builder Company Deleted successfully')
                window.location.reload();
            },
        });
            }
            else
                return
        }


</script>

I_Value.WebApp/IValue/Views/BuilderAndCompany/CompanyMaster.cshtml
@model  I_Value.WebApp.Models.VMBuilderGroupMaster
@{
    ViewBag.Title = "CompanyMaster";
    Layout = "~/Views/Shared/_IvalueMasterPage.cshtml";
}

<form action="~/BuilderAndCompany/AddCompanyMaster" method="post">
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="padding-left:10px;">Add Builder company Details </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="content bg">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-lg-12 padd0">
                            <div class="card">
                                <div class="card-body card-block">
                                    <div class="row">
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Builder Group Name:</label>
                                                @*<select class="form-control">
                        <option>Paranjape Schemes</option>
                        <option>Rohan Builders</option>
                        <option>Sobha Builders</option>
                    </select>*@
                                                @Html.DropDownListFor(m => m.SelectedBuilderGroupMasterID, new SelectList(Model.BuilderGroupList, "Builder_Group_Master_ID", "BuilderGroupName"), "Please Select", new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Builder Company Name:</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Company_Name, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div style="clear:both"></div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Legal Address 1:</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Legal_Address1, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Legal Address 2:</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Legal_Address2, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>

                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">City </label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_C_City, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">District</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_C_District, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">State</label>
                                                @*<select name="" class="form-control">
                        <option>Select</option>
                        <option>Maharashtra</option>
                        <option>Karnataka</option>
                        <option>Madhya Pradesh</option>
                    </select>*@
                                                @Html.DropDownListFor(m => m.SelectedBuilderCompanyStateID, new SelectList(Model.ival_StatesList, "State_ID", "State_Name"), "Please Select", new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Pin code</label>
                                                @*<select name="" class="form-control">
                        <option>Select</option>
                        <option>410251</option>
                        <option>421058</option>
                        <option>421508</option>
                    </select>*@
                                                @Html.DropDownListFor(m => m.SelectedBuilderCompanyPincodeID, new SelectList(Model.PincodeList, "Lookup_ID", "Lookup_Value"), "Please Select", new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Postal Address 1:</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Postal_Address1, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Postal Address 2:</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Postal_Address1, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">City </label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Postal_City, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">District</label>
                                                @*<input type="text" id="company" class="form-control">*@
                                                @Html.EditorFor(model => model.ival_BuilderCompanyMaster.Builder_Postal_District, new { htmlAttributes = new { @class = "form-control", id = "txtfname" } })
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">State</label>
                                                @*<select name="" class="form-control">
                        <option>Select</option>
                        <option>Maharashtra</option>
                        <option>Karnataka</option>
                        <option>Madhya Pradesh</option>
                    </select>*@
                                                @Html.DropDownListFor(m => m.SelectedBuilderPostalStateID, new SelectList(Model.ival_StatesList, "State_ID", "State_Name"), "Please Select", new { @class = "form-control" })


                                            </div>
                                        </div>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="company" class=" form-control-label">Pin code</label>
                                                @*<select name="" class="form-control">
                        <option>Select</option>
                        <option>410251</option>
                        <option>421058</option>
                        <option>421508</option>
                    </select>*@
                                                @Html.DropDownListFor(m => m.SelectedBuilderPostalPincodeID, new SelectList(Model.PincodeList, "Lookup_ID", "Lookup_Value"), "Please Select", new { @class = "form-control" })

                                            </div>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                    @*<a class="btn btn-success btn-sm" href="@Url.Action("ViewCompany","BuilderAndCompany")">Submit</a>*@
                                    <input type="submit" value="Submit" class="btn btn-success btn-sm pull-right" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .animated -->
        </div>
        <!-- Default box -->
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
    </form>