I_Value.WebApp/IValue/Controllers/BranchController.cs
using I_Value.WebApp.Models;
using IValuePublishProject.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IvalueDataAccess;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Globalization;

namespace I_Value.WebApp.Controllers
{
    public class BranchController : Controller
    {
        SQLDataAccess sqlDataAccess;
        Hashtable hInputPara;
        VMBranchMaster vMBranchMaster;
        IvalueDataModel Datamodel = new IvalueDataModel();
        // GET: Branch
        public ActionResult Index()
        {
            try
            {
                hInputPara = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                DataTable dtBranch = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetBranch");

                List<ival_BranchMaster> listbranch = new List<ival_BranchMaster>();

                if (dtBranch.Rows.Count > 0&& dtBranch!=null)

                {
                    for (int i = 0; i < dtBranch.Rows.Count; i++)
                    {

                        listbranch.Add(new ival_BranchMaster
                        {
                            Branch_ID= Convert.ToInt32(dtBranch.Rows[i]["Branch_ID"]),
                            Branch_Code= Convert.ToString(dtBranch.Rows[i]["Branch_Code"]),
                            Branch_Name = Convert.ToString(dtBranch.Rows[i]["Branch_Name"]),
                            Branch_State = Convert.ToString(dtBranch.Rows[i]["Branch_State"]),
                            Lessor_First_Name = Convert.ToString(dtBranch.Rows[i]["First_Name"])
                           
                        });


                    }
                }
                return View(listbranch);

            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
            //return View();
        }
        
        public ActionResult AddNewBranch()
        {
            VMBranchMaster vMBranchMaster = new VMBranchMaster();
            vMBranchMaster.ival_StatesList = GetState();
            vMBranchMaster.ival_CitiesList = GetCity();
            //vMBranchMaster.pincodeList = GetPincode();
            vMBranchMaster.ival_DistrictsList = GetDistricts();
            vMBranchMaster.ival_LocalityList = GetLocality();

            vMBranchMaster.AccountTypeList = GetAccountType();
            vMBranchMaster.branchHeadsList = GetBranchHeadList();
            return View(vMBranchMaster);
        }

        [HttpPost]
        public ActionResult AddNewBranch(String str)
        {
            string resultStr = string.Empty;
            DataTable list1 = (DataTable)JsonConvert.DeserializeObject(str, (typeof(DataTable)));

            try
            {
                IEnumerable<ival_States> ival_StatesList = GetState();
                var branchState = ival_StatesList.AsEnumerable().Where(row => row.State_ID == vMBranchMaster.SelectedBranchStateID).Select(row => row.State_Name.ToString());

                IEnumerable<ival_Locality> ival_LocalityList = GetLocality();
                var branchPincode = ival_LocalityList.AsEnumerable().Where(row => row.Loc_Id == vMBranchMaster.SelectedBranchPincode).Select(row => row.Loc_Name.ToString());

                for (int i = 0; i < list1.Rows.Count; i++)
                {
                    hInputPara = new Hashtable();
                    sqlDataAccess = new SQLDataAccess();

                    /*if (Convert.ToBoolean(list1.Rows[i]["Is_Leased"]))
                    {*/
                    /* var lessorState = ival_StatesList.AsEnumerable().Where(row => row.State_ID == vMBranchMaster.SelectedLessorStateID).Select(row => row.State_Name.ToString());
                     var landlordState = ival_StatesList.AsEnumerable().Where(row => row.State_ID == vMBranchMaster.SelectedLandlordStateID).Select(row => row.State_Name.ToString());
                     vMBranchMaster.Lessor_State = lessorState.FirstOrDefault();
                     vMBranchMaster.LandLord_State = landlordState.FirstOrDefault();

                     var lessorPincode = pincodeList.AsEnumerable().Where(row => row.Loc_Id == vMBranchMaster.SelectedLessorPincode).Select(row => row.Loc_Name.ToString());
                     var landlordPincode = pincodeList.AsEnumerable().Where(row => row.Loc_Id == vMBranchMaster.SelectedLandlordPincode).Select(row => row.Loc_Name.ToString());*/
                    //if (Convert.ToBoolean(list1.Rows[i]["Is_Leased"]))
                    if (Convert.ToBoolean(list1.Rows[i]["Is_Leased"]))
                    {
                       /* if (Convert.ToString(list1.Rows[i]["Lessor_Fname"]) != "")
                    {*/

                        hInputPara.Add("@Is_Leased", 1);
                        hInputPara.Add("@Lessor_First_Name", Convert.ToString(list1.Rows[i]["Lessor_Fname"]));
                        hInputPara.Add("@Lessor_Middle_Name", Convert.ToString(list1.Rows[i]["Lessor_Mname"]));
                        hInputPara.Add("@Lessor_Last_Name", Convert.ToString(list1.Rows[i]["Lessor_Lname"]));
                        hInputPara.Add("@Lessor_Address1", Convert.ToString(list1.Rows[i]["Lessor_Address1"]));
                        hInputPara.Add("@Lessor_Address2", Convert.ToString(list1.Rows[i]["Lessor_Address2"]));
                        hInputPara.Add("@Lessor_City", Convert.ToString(list1.Rows[i]["Lessor_City1"]));
                        hInputPara.Add("@Lessor_Locality", Convert.ToString(list1.Rows[i]["Lessor_City"]));
                        hInputPara.Add("@Lessor_District", Convert.ToString(list1.Rows[i]["Lessor_Dist"]));
                        hInputPara.Add("@Lessor_State", Convert.ToString(list1.Rows[i]["Lessor_State"]));
                        hInputPara.Add("@Lessor_Pincode", Convert.ToInt32(list1.Rows[i]["Lessor_Pin"]));
                        hInputPara.Add("@Lessor_Contact_Num", Convert.ToString(list1.Rows[i]["Lessor_Contact"]));
                        hInputPara.Add("@Lessor_Email_ID", Convert.ToString(list1.Rows[i]["Lessor_Email"]));

                        /*var dateString = list1.Rows[i]["Lease_Start_Date"].ToString();
                        var format = "dd/MM/yyyy";
                        if (dateString != "")
                        {
                            var dateTime = DateTime.ParseExact(dateString, format, CultureInfo.InvariantCulture);
                            hInputPara.Add("@Lease_Start_Date", dateTime);
                        }
                        var dateString1 = list1.Rows[i]["Lease_End_Date"].ToString();
                        var format1 = "dd/MM/yyyy";
                        if (dateString1 != "")
                        {
                            var dateTime = DateTime.ParseExact(dateString1, format1, CultureInfo.InvariantCulture);
                            hInputPara.Add("@Lease_End_Date", dateTime);
                        }*/

                        hInputPara.Add("@Lease_Start_Date", CDateTime(list1.Rows[i]["Lease_Start_Date"].ToString()));
                       // hInputPara.Add("@Lease_Start_Date", Convert.ToString(list1.Rows[i]["Lease_Start_Date"]));
                        hInputPara.Add("@Lease_End_Date", CDateTime(list1.Rows[i]["Lease_End_Date"].ToString()));
                       //hInputPara.Add("@Lease_End_Date", Convert.ToString(list1.Rows[i]["Lease_End_Date"]));
                        hInputPara.Add("@Monthly_Rent", Convert.ToString(list1.Rows[i]["Monthly_Rent"]));
                        hInputPara.Add("@Maintaince_Charges", Convert.ToString(list1.Rows[i]["Maintaince_Charges"]));
                        hInputPara.Add("@Other_Charges", Convert.ToString(list1.Rows[i]["Other_Charges"]));

                        hInputPara.Add("@LandLord_Bank", Convert.ToString(list1.Rows[i]["LL_Bank"]));
                        hInputPara.Add("@LandLord_Branch", Convert.ToString(list1.Rows[i]["LL_Branch"]));
                        hInputPara.Add("@LandLord_Address1", Convert.ToString(list1.Rows[i]["LL_Address1"]));
                        hInputPara.Add("@LandLord_Address2", Convert.ToString(list1.Rows[i]["LL_Address2"]));
                        hInputPara.Add("@LandLord_City", Convert.ToString(list1.Rows[i]["LL_City1"]));
                        hInputPara.Add("@LandLord_Locality", Convert.ToString(list1.Rows[i]["LL_City"]));
                        hInputPara.Add("@LandLord_District", Convert.ToString(list1.Rows[i]["LL_Dist"]));
                        hInputPara.Add("@LandLord_State", Convert.ToString(list1.Rows[i]["LL_State"]));
                        hInputPara.Add("@LandLord_Pincode", Convert.ToInt32(list1.Rows[i]["LL_Pin"]));
                        hInputPara.Add("@Account_Type", Convert.ToString(list1.Rows[i]["Acc_Type"]));
                        hInputPara.Add("@Account_Number", Convert.ToString(list1.Rows[i]["Acc_No"]));
                        hInputPara.Add("@IFSC_Num", Convert.ToString(list1.Rows[i]["IFSC_Num"]));
                        hInputPara.Add("@PAN_Num", Convert.ToString(list1.Rows[i]["PAN_Num"]));
                        hInputPara.Add("@GSTIN_Num", Convert.ToString(list1.Rows[i]["GSTIN_Num"]));

                        hInputPara.Add("@Branch_Code", Convert.ToString(list1.Rows[i]["Br_Code"]));
                        hInputPara.Add("@Branch_Name", Convert.ToString(list1.Rows[i]["Br_Name"]));
                        hInputPara.Add("@Branch_Address1", Convert.ToString(list1.Rows[i]["Br_Addr1"]));
                        hInputPara.Add("@Branch_Address2", Convert.ToString(list1.Rows[i]["Br_Addr2"]));
                        hInputPara.Add("@Branch_City", Convert.ToString(list1.Rows[i]["Br_City"]));
                        hInputPara.Add("@Branch_District", Convert.ToString(list1.Rows[i]["Br_Dist"]));

I_Value.WebApp/IValue/Views/Branch/Index.cshtml
@model IEnumerable<IValuePublishProject.Models.ival_BranchMaster>

@{

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IvalueMasterPage.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="padding-left:10px;"> i-Value Branches </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="content bg">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="search-container">
                                    @using (Html.BeginForm("Index", "Branch", FormMethod.Post))
                                    {
                                       
                                        @*<a href="@Url.Action("AddNewBranch", "Branch")" class="btn btn-success btn-sm pull-right">Add New Branch</a>*@
                                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("AddNewBranch","Branch")">Add New Branch</a>
                                    }
                                </div>
                                <br>
                                <br />
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered tblss">
                                        <thead>
                                            <tr>
                                                <th width="274">Branch Code</th>
                                                <th width="274"> Branch Name</th>
                                                <th width="253">State</th>
                                                <th width="360">Branch Head</th>
                                                <th width="26">View</th>
                                                <th width="26">Edit</th>
                                                <th width="26">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Branch_Code)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Branch_Name)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Branch_State)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Lessor_First_Name)
                                                    </td>
                                                    <td>
                                                        <a href="@Url.Action("ViewBranchDetails", "Branch", new { id = item.Branch_ID })">
                                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="@Url.Action("EditBranch", "Branch", new { id = item.Branch_ID })">
                                                            <i class="fa fa-edit"></i>
                                                        </a>
                                                    </td>

                                                    <td>
                                                        @*<a href="@Url.Action("Delete", "Branch", new { id = item.Branch_ID })">
            <i class="fa fa-trash" aria-hidden="true"></i>
        </a>*@
                                                        <a>
                                                            <i class="fa fa-trash" aria-hidden="true" onclick="ConfirmDelete(@item.Branch_ID);"></i>
                                                        </a>
                                                    </td>

                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .animated -->
        </div>
        <!-- Default box -->
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script>
             function ConfirmDelete(Id) {
            var str = Id;
            var x = confirm("Are you sure you want to delete?");
            if (x) {
               $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "Branch")',
            data: { ID: str },
            success: function (data) {
                //$("#divLoader").hide();
                   alert('Employee Deleted successfully')
                window.location.reload();
            },
        });
            }
            else
                return
        }
</script>